"""Add_hba1c_offset

Revision ID: 27f5af090c2c
Revises: 5926ed0820b6
Create Date: 2026-02-04 14:14:39.331867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f5af090c2c'
down_revision: Union[str, Sequence[str], None] = '5926ed0820b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaires', sa.Column('target_hba1c', sa.Float(), nullable=True))
    op.add_column('questionnaires', sa.Column('target_hba1c_date', sa.DateTime(), nullable=True))
    op.add_column('questionnaires', sa.Column('last_lab_hba1c', sa.Float(), nullable=True))
    op.add_column('questionnaires', sa.Column('hba1c_offset', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaires', 'hba1c_offset')
    op.drop_column('questionnaires', 'last_lab_hba1c')
    op.drop_column('questionnaires', 'target_hba1c_date')
    op.drop_column('questionnaires', 'target_hba1c')
    # ### end Alembic commands ###
