"""Add physical_limitations to Questionnaire

Revision ID: 467ca83eb72e
Revises: 66a0c100b404
Create Date: 2026-02-09 08:53:39.870661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467ca83eb72e'
down_revision: Union[str, Sequence[str], None] = '66a0c100b404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaires', sa.Column('physical_limitations', sa.String(), nullable=True))
    op.add_column('questionnaires', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaires', 'name')
    op.drop_column('questionnaires', 'physical_limitations')
    # ### end Alembic commands ###
